theme: jekyll-theme-minimal
title: Capitals
description: Google Docs add-on for modifying capitalization of text.
logo: https://raw.githubusercontent.com/burnnat/capitals/master/assets/Capitals-Icon.png
show_downloads: false
